'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Electricity_Billing_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _28018() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("28018", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _280181() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("280181", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3716300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3716300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bde512f6ec6520399cab7a2fe3dc6dfb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bde512f6ec6520399cab7a2fe3dc6dfb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blogimage800x600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blogimage800x600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property consumer_rights_pic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consumer-rights-pic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property d2e7129d137e432fa639c3ebb44b1e28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d2e7129d137e432fa639c3ebb44b1e28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property electronic_energy_meter_1519122317_3664477() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("electronic-energy-meter-1519122317-3664477", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Growth_of_the_wind_energy_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Growth-of-the-wind-energy-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Material_Colors_iPhone_Wallpaper_iphoneswallpapers_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Material-Colors-iPhone-Wallpaper-iphoneswallpapers_com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maxresdefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxresdefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property modern_wood_flooring() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modern-wood-flooring", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property output_20_22_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("output_20_22_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Samsung_Galaxy_S5_carbon_fibre_design_hope() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Samsung-Galaxy-S5-carbon-fibre-design-hope", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property savingelectricity3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savingelectricity3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property talavera_tile_design_13bb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("talavera-tile-design-13bb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wind_power() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wind-power", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wind_power_2156_1120() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wind-power-2156-1120", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wind_power1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wind-power1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windenergy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windenergy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
